# Generated by Django 5.0.3 on 2024-03-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us Entries'},
        ),
    ]
